export const userBreadCumbs = {
    'ban-ghe': 'Tất Cả Bàn & Ghế',
    'ban-an': 'Bàn Ăn',
    'ban-trang-diem': 'Bàn Trang Điểm',
    'ban-tra': 'Bàn Trà',
    'ban-ghe-lam-viec': 'Bàn & Ghế Làm Việc',
    'ghe-don': 'Ghế Đơn',
    'ban-ghe-truong-ky': 'Bàn & Ghế Trường Kỷ Cổ',
    'ban-ghe-sofa': 'Bàn & Ghế Sofa',
    tu: 'Tất Cả Tủ',
    'tu-tho': 'Tủ Thờ',
    'tu-bay-do': 'Tủ Bày Đồ',
    'tu-chua': 'Tủ Chùa',
    'tu-quan-ao': 'Tủ Quần Áo',
    'tu-sach': 'Tủ Sách',
    'tu-loai-khac': 'Tủ Loại Khác',
    ke: 'Tất Cả Kệ',
    'ke-tivi': 'Kệ Tivi',
    'ke-trang-tri': 'Kệ Trang Trí',
    'ke-loai-khac': 'Kệ Loại Khác',
    giuong: 'Tất Cả Giường',
    'giuong-cu-xua': 'Giường Cũ Xưa',
    'giuong-hien-dai': 'Giường Hiện Đại',
    'tuong-&-tranh': 'Tất Cả Tượng & Tranh',
    'tuong-go': 'Tượng Gỗ',
    'tuong-su': 'Tượng Sứ',
    'tuong-dong': 'Tượng Đồng',
    'tuong-da': 'Tượng Đá',
    'tranh-go': 'Tranh Gỗ',
    'tranh-son-dau': 'Tranh Sơn Dầu',
    'tranh-da': 'Tranh Đá',
    'trang-tri-&-khac': 'Tất Cả Trang Trí & Khác',
    'do-gom': 'Đồ Gốm',
    ruong: 'Rương',
    'den-tran': 'Đèn Trần',
};
export const adminBreadCumbs = [
    { url: '/admin/dashboard', urlTile: 'Dashboard', name: 'Dashboard' },
    { url: '/admin/product/list', urlTile: 'Product', name: 'List Product' },
    { url: '/admin/product/add', urlTile: 'Product', name: 'Add Product' },
    { url: '/admin/material/list', urlTile: 'Material', name: 'List Material' },
    { url: '/admin/category/list', urlTile: 'Category', name: 'List Category' },
    { url: '/admin/home/banner', urlTile: 'Home', name: 'Image Banner' },
    { url: '/admin/home/customer', urlTile: 'Home', name: 'Image Customer' },
    { url: '/admin/home/featuredProduct', urlTile: 'Home', name: 'Featured Product' },
    { url: '/admin/home/bannerOnMobile', urlTile: 'Home', name: 'Image Banner On Mobile' },
    //..thêm nữa
];
