export const userBreadCumbs: any = {
    'ban-ghe': 'Tất Cả Bàn Ghế',
    'ban-ghe-an': 'Bàn Ghế Ăn',
    'ban-ghe-tra': 'Bàn Ghế Trà',
    'ban-ghe-lam-viec': 'Bàn Ghế Làm Việc',
    'ban-ghe-salon': 'Bàn Ghế Salon',
    'ban-ghe-truong-ky': 'Bàn Ghế Trường Kỷ',
    'ban-ghe-sofa': 'Bàn Ghế Sofa',
    'ban-ghe-khac': 'Bàn Ghế Khác',
    'ban-ghe-cafe': 'Bàn Ghế Cafe',
    'ban-ghe-trang-diem': 'Bàn Ghế Trang Điểm',
    'ban-ghe-phong-khach': 'Bàn Ghế Phòng Khách',
    // TỦ
    tu: 'Tất Cả Tủ',
    'tu-tho': 'Tủ Thờ',
    'tu-bay-do': 'Tủ Bày Đồ',
    'tu-chua': 'Tủ Chùa',
    'tu-thuoc': 'Tủ Thuốc',
    'tu-quan-ao': 'Tủ Quần Áo',
    'tu-sach': 'Tủ Sách',
    'tu-loai-khac': 'Tủ Loại Khác',
    ke: 'Tất Cả Kệ',
    'ke-tivi': 'Kệ Tivi',
    'ke-trang-tri': 'Kệ Trang Trí',
    'ke-loai-khac': 'Kệ Loại Khác',
    'ke-sach': 'Kệ Sách',
    giuong: 'Tất Cả Giường',
    'giuong-cu-xua': 'Giường Cũ Xưa',
    'giuong-hien-dai': 'Giường Hiện Đại',
    'giuong-loai-khac': 'Giường Loại Khác',
    // TƯỢNG
    'tuong-va-tranh': 'Tất Cả Tượng Và Tranh',
    'tuong-go': 'Tượng Gỗ',
    'tuong-su': 'Tượng Sứ',
    'tuong-dong': 'Tượng Đồng',
    'tuong-da': 'Tượng Đá',
    'tuong-loai-khac': 'Tượng Loại Khác',
    //TRANH
    'tranh-da': 'Tranh Đá',
    'tranh-son-mai': 'Tranh Sơn Mài',
    'tranh-go-kham-oc': 'Tranh Gỗ Khảm Ốc',
    'tranh-son-dau': 'Tranh Sơn Dầu',
    'tranh-dieu-khac': 'Tranh Điêu Khắc',
    'tranh-loai-khac': 'Tranh Loại Khác',
    // KHÁC
    'trang-tri-va-khac': 'Tất Cả Trang Trí Và Khác',
    'do-gom-su': 'Đồ Gốm Sứ',
    ruong: 'Rương',
    'den-tran': 'Đèn Trần',
    'den-ngu': 'Đèn Ngủ',
    'vali-co-xua': 'Vali Cổ Xưa',
    'ban-tho': 'Bàn Thờ',
    khac: 'Khác',
};
export const adminBreadCumbs = [
    { url: '/admin/dashboard', urlTile: 'Dashboard', name: 'Dashboard' },
    { url: '/admin/product/list', urlTile: 'Product', name: 'List Product' },
    { url: '/admin/product/add', urlTile: 'Product', name: 'Add Product' },
    { url: '/admin/material/list', urlTile: 'Material', name: 'List Material' },
    { url: '/admin/category/list', urlTile: 'Category', name: 'List Category' },
    { url: '/admin/home/banner', urlTile: 'Home', name: 'Image Banner' },
    { url: '/admin/home/customer', urlTile: 'Home', name: 'Image Customer' },
    { url: '/admin/home/featuredProduct', urlTile: 'Home', name: 'Featured Product' },
    { url: '/admin/home/bannerOnMobile', urlTile: 'Home', name: 'Image Banner On Mobile' },
    { url: '/admin/news/list', urlTile: 'News', name: 'List News' },
    { url: '/admin/home/featuredNews', urlTile: 'Home', name: 'Featured News' },
    //..thêm nữa
];
