# Use an official Node.js image as a base image
FROM node:lts

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --force

# Copy the rest of the application code
COPY . .

# Build the Next.js app
# RUN npm run build

# Expose the Next.js app port
EXPOSE 3000

# Start the Next.js app
CMD ["npm", "start"]
