import { Poppins } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import '@/styles/GobalStyles.scss';
import '@/styles/SwiperCustom.scss';

import Footer from '@/Layout/components/Footer';
import AnouBar from '@/Layout/components/AnouBar';
import Chat from '@/Layout/components/Chat';
import Header from '@/Layout/components/Header';
import ProviderRedux from '@/redux/ProviderRedux';

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['200', '300', '400', '500', '600', '700'],
    style: ['italic', 'normal'],
});

export const metadata = {
    title: 'Đồ Gỗ Triệu',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.ico',
    },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
            <body className={poppins.className}>
                <main>
                    <ProviderRedux>
                        <AnouBar />
                        <Header />
                        {children}
                        <Footer />
                        <Chat />
                    </ProviderRedux>
                </main>
            </body>
        </html>
    );
}
