import { Poppins } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import '../styles/GobalStyles.scss';

import Footer from '@/Layout/components/Footer';
import Header from '@/Layout/components/Header';
import AnouBar from '@/Layout/components/AnouBar';

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['200', '300', '400', '500', '600'],
    style: ['italic', 'normal'],
});

export const metadata = {
    title: 'Đồ Gỗ Triệu',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.ico',
    },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <AnouBar />
                <Header />
                <div className="App">{children}</div>
                <Footer />
            </body>
        </html>
    );
}
